In [2]:
!pip install pandas
!pip install numpy

Collecting pandas
  Using cached pandas-2.2.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.2.4-cp312-cp312-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\ml\rekomendasi-destinasi-wisata\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in d:\ml\rekomendasi-destinasi-wisata\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-2.2.3-cp312-cp312-win_amd64.whl (11.5 MB)
Downloading numpy-2.2.4-cp312-cp312-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ----- ---------------------------------- 1.8/12.6 MB 11.2 MB/s eta 0:00:01
   -------------- ------------------------- 4.5/12.6 MB 12.2 MB/s eta 0:00:01
   ----------------------- ---------------- 7.3/12.6 MB 12.6 MB/s eta 0:00:01
   ------------------------------- -------- 10.0/12.6 MB 12.7 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.6 MB 12.9 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 12.6 MB/s eta 0:00:00
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-2.2.4 pandas-2.2.3 pytz-2025.2 tzdata-2025.2

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: numpy in d:\ml\rekomendasi-destinasi-wisata\.venv\lib\site-packages (2.2.4)

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
import numpy as np

In [4]:
reviews = 'results/reviews.csv'
details = 'results/details.csv'

reviews_df = pd.read_csv(reviews)
details_df = pd.read_csv(details)

In [6]:
reviews_df.head()

,nama_destinasi,username,komentar,rating,tanggal
0,Ramayana Ballet Prambanan,MK,"Selalu suka dengan pertunjukan nya, sedih krn ...","5,0\n/5",8 Apr 2025
1,Ramayana Ballet Prambanan,Miranda Tjahjadi,Sangatt sangatt baguss dan sangattt recomended...,"5,0\n/5",7 Apr 2025
2,Ramayana Ballet Prambanan,Riqi Riqi,Pengalaman pertunjukan kebudayaan jawa terbaik,"5,0\n/5",5 Apr 2025
3,Ramayana Ballet Prambanan,Muhammad Iqbal,Ngk nyesalll nnton ini walaupun di indoor tapi...,"5,0\n/5",4 Mar 2025
4,Ramayana Ballet Prambanan,Intan Ama Yuniari,bagus bgttttttttttttttttttttttrtttrttrrttt,"5,0\n/5",1 Mar 2025

In [7]:
details_df.head()

,nama_destinasi,rating_destinasi,harga,lokasi
0,Ramayana Ballet Prambanan,"4,8/5\n(\n290 Review\n)",IDR 150.000,"Kalasan, Sleman"
1,Legenda Roro Jonggrang Prambanan,"4,7/5\n(\n78 Review\n)",IDR 100.000,"Prambanan, Sleman"
2,Tiket Masuk Candi Prambanan,"4,5/5\n(\n3.5rb Review\n)",IDR 50.000,"Prambanan, Sleman"
3,Candi Ratu Boko,"4,8/5\n(\n182 Review\n)",IDR 21.000,"Prambanan, Sleman"
4,HeHa Forest,4/5\n(\n1 Review\n),IDR 25.000,"Pakem, Sleman"

In [8]:
reviews_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4035 entries, 0 to 4034
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   nama_destinasi  4035 non-null   object
 1   username        4021 non-null   object
 2   komentar        4035 non-null   object
 3   rating          4035 non-null   object
 4   tanggal         4035 non-null   object
dtypes: object(5)
memory usage: 157.7+ KB

In [9]:
details_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   nama_destinasi    17 non-null     object
 1   rating_destinasi  17 non-null     object
 2   harga             17 non-null     object
 3   lokasi            17 non-null     object
dtypes: object(4)
memory usage: 676.0+ bytes

In [14]:
destinasi_review = reviews_df['nama_destinasi'].unique().tolist()
destinasi_detail = details_df['nama_destinasi'].unique().tolist()

print(f"destinasi reviews {len(destinasi_review)} : ")
print(f"{destinasi_review}")

print("\n")
print(f"destinasi details {len(destinasi_detail)}")
print(f"{destinasi_detail}")

destinasi reviews 13 :
['Ramayana Ballet Prambanan', 'Legenda Roro Jonggrang Prambanan', 'Tiket Masuk Candi Prambanan', 'Candi Ratu Boko', 'HeHa Forest', 'Official Tickets | Ramayana Ballet Purawisata – 48 Years', 'La Li Sa European Park', 'Waterboom Jogja', 'De MANGOL VIEW', 'The Legend of Roro Jonggrang Ticket in Yogyakarta', 'Jomblang Cave Experience in Yogyakarta', 'Merapi Jeep Ticket in Yogyakarta', 'Merapi Park Jogja']


destinasi details 17
['Ramayana Ballet Prambanan', 'Legenda Roro Jonggrang Prambanan', 'Tiket Masuk Candi Prambanan', 'Candi Ratu Boko', 'HeHa Forest', 'Official Tickets | Ramayana Ballet Purawisata – 48 Years', 'La Li Sa European Park', 'Waterboom Jogja', 'De MANGOL VIEW', 'Kaliurang Park Botanical Garden', 'The Legend of Roro Jonggrang Ticket in Yogyakarta', 'Jomblang Cave Experience in Yogyakarta', 'Merapi Jeep Ticket in Yogyakarta', 'Merapi Park Jogja', 'Java Puppets Museum Admission Ticket', 'Private Borobudur Sunrise and Prambanan Temple Tour', 'Borobudur Temple Private Tour with German Speaking Guide']

In [16]:
tidak_ada_di_reviews = list(set(destinasi_detail) - set(destinasi_review))
print(f"🔵 Destinasi yang ADA DI DETAILS tapi TIDAK DI REVIEWS ({len(tidak_ada_di_reviews)}):")
for i, d in enumerate(tidak_ada_di_reviews, 1):
    print(f"{i}. {d}")

🔵 Destinasi yang ADA DI DETAILS tapi TIDAK DI REVIEWS (4):
1. Java Puppets Museum Admission Ticket
2. Borobudur Temple Private Tour with German Speaking Guide
3. Kaliurang Park Botanical Garden
4. Private Borobudur Sunrise and Prambanan Temple Tour

In [28]:
destinations_df = pd.merge(
    reviews_df,
    details_df,
    on='nama_destinasi',
    how='inner'
)

destinations_df.head()

,nama_destinasi,username,komentar,rating,tanggal,rating_destinasi,harga,lokasi
0,Ramayana Ballet Prambanan,MK,"Selalu suka dengan pertunjukan nya, sedih krn ...","5,0\n/5",8 Apr 2025,"4,8/5\n(\n290 Review\n)",IDR 150.000,"Kalasan, Sleman"
1,Ramayana Ballet Prambanan,Miranda Tjahjadi,Sangatt sangatt baguss dan sangattt recomended...,"5,0\n/5",7 Apr 2025,"4,8/5\n(\n290 Review\n)",IDR 150.000,"Kalasan, Sleman"
2,Ramayana Ballet Prambanan,Riqi Riqi,Pengalaman pertunjukan kebudayaan jawa terbaik,"5,0\n/5",5 Apr 2025,"4,8/5\n(\n290 Review\n)",IDR 150.000,"Kalasan, Sleman"
3,Ramayana Ballet Prambanan,Muhammad Iqbal,Ngk nyesalll nnton ini walaupun di indoor tapi...,"5,0\n/5",4 Mar 2025,"4,8/5\n(\n290 Review\n)",IDR 150.000,"Kalasan, Sleman"
4,Ramayana Ballet Prambanan,Intan Ama Yuniari,bagus bgttttttttttttttttttttttrtttrttrrttt,"5,0\n/5",1 Mar 2025,"4,8/5\n(\n290 Review\n)",IDR 150.000,"Kalasan, Sleman"

In [29]:
destinations_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4035 entries, 0 to 4034
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   nama_destinasi    4035 non-null   object
 1   username          4021 non-null   object
 2   komentar          4035 non-null   object
 3   rating            4035 non-null   object
 4   tanggal           4035 non-null   object
 5   rating_destinasi  4035 non-null   object
 6   harga             4035 non-null   object
 7   lokasi            4035 non-null   object
dtypes: object(8)
memory usage: 252.3+ KB

## **HANDLING NULL**

In [30]:
destinations_df.isna().sum()

nama_destinasi       0
username            14
komentar             0
rating               0
tanggal              0
rating_destinasi     0
harga                0
lokasi               0
dtype: int64

In [34]:
destinations_df[destinations_df['username'].isnull()]

,nama_destinasi,username,komentar,rating,tanggal,rating_destinasi,harga,lokasi
691,Tiket Masuk Candi Prambanan,NaN,Kereen arsitektur candi nya dan diperkaya deng...,"5,0\n/5",4 Aug 2024,"4,5/5\n(\n3.5rb Review\n)",IDR 50.000,"Prambanan, Sleman"
837,Tiket Masuk Candi Prambanan,NaN,Pesan tiket masuk ke Candi Prambanan lewat tik...,"5,0\n/5",4 Jun 2024,"4,5/5\n(\n3.5rb Review\n)",IDR 50.000,"Prambanan, Sleman"
1244,Tiket Masuk Candi Prambanan,NaN,Lebih murah dan memudahkan.,"5,0\n/5",27 Dec 2023,"4,5/5\n(\n3.5rb Review\n)",IDR 50.000,"Prambanan, Sleman"
1355,Tiket Masuk Candi Prambanan,NaN,Tempat wisata bersama keluarga seruu,"5,0\n/5",27 Nov 2023,"4,5/5\n(\n3.5rb Review\n)",IDR 50.000,"Prambanan, Sleman"
1436,Tiket Masuk Candi Prambanan,NaN,"Kereeen bgt, next time ke Prambanan lagii","5,0\n/5",6 Oct 2023,"4,5/5\n(\n3.5rb Review\n)",IDR 50.000,"Prambanan, Sleman"
1459,Tiket Masuk Candi Prambanan,NaN,Bagus bangey reccomended,"5,0\n/5",30 Sep 2023,"4,5/5\n(\n3.5rb Review\n)",IDR 50.000,"Prambanan, Sleman"
2533,Tiket Masuk Candi Prambanan,NaN,"Sangat menyenangkan, tempatnya bersih","5,0\n/5",18 Sep 2022,"4,5/5\n(\n3.5rb Review\n)",IDR 50.000,"Prambanan, Sleman"
2534,Tiket Masuk Candi Prambanan,NaN,Sangat menyenangkan bisa kembali berwisata ke ...,"5,0\n/5",18 Sep 2022,"4,5/5\n(\n3.5rb Review\n)",IDR 50.000,"Prambanan, Sleman"
2909,Tiket Masuk Candi Prambanan,NaN,"seru bangetttt, walaupun siang hari panas-pana...","4,0\n/5",28 Aug 2024,"4,5/5\n(\n3.5rb Review\n)",IDR 50.000,"Prambanan, Sleman"
3466,Candi Ratu Boko,NaN,Bagus pemandangan sunsetnya Datang ke sini bet...,"5,0\n/5",13 Oct 2024,"4,8/5\n(\n182 Review\n)",IDR 21.000,"Prambanan, Sleman"
3636,Official Tickets | Ramayana Ballet Purawisata ...,NaN,Makan malam enak dan baletnya menyenangkan,"5,0\n/5",22 Nov 2024,"4,8/5\n(\n103 Review\n)",IDR 147.000,"Mergangsan, Yogyakarta"
3637,Official Tickets | Ramayana Ballet Purawisata ...,NaN,Bagus dan menyenangkan. Makan malamnya jg enak,"5,0\n/5",22 Nov 2024,"4,8/5\n(\n103 Review\n)",IDR 147.000,"Mergangsan, Yogyakarta"
3808,Waterboom Jogja,NaN,Seruu abisssss cuman ada satu wahana yang di t...,"5,0\n/5",8 Oct 2023,"4,5/5\n(\n367 Review\n)",IDR 51.880,"Ngemplak, Sleman"
3820,Waterboom Jogja,NaN,SERU PARAHHH. Really worth time and money. Wil...,"5,0\n/5",1 Sep 2023,"4,5/5\n(\n367 Review\n)",IDR 51.880,"Ngemplak, Sleman"

In [35]:
# drop kolom username
destinations_df.drop(columns="username", inplace=True)

In [36]:
destinations_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4035 entries, 0 to 4034
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   nama_destinasi    4035 non-null   object
 1   komentar          4035 non-null   object
 2   rating            4035 non-null   object
 3   tanggal           4035 non-null   object
 4   rating_destinasi  4035 non-null   object
 5   harga             4035 non-null   object
 6   lokasi            4035 non-null   object
dtypes: object(7)
memory usage: 220.8+ KB

In [45]:
# shuffle dataset
destinations_df = destinations_df.sample(frac=1).reset_index(drop=True)

In [46]:
destinations_df.head()

,nama_destinasi,komentar,rating,tanggal,rating_destinasi,harga,lokasi
0,Ramayana Ballet Prambanan,Kalau sudah booking prosesnya cepet aja tingga...,"4,0\n/5",20 May 2023,"4,8/5\n(\n290 Review\n)",IDR 150.000,"Kalasan, Sleman"
1,Ramayana Ballet Prambanan,Butifulfhdhdjdudddbdbd,"3,0\n/5",11 Feb 2023,"4,8/5\n(\n290 Review\n)",IDR 150.000,"Kalasan, Sleman"
2,Tiket Masuk Candi Prambanan,Kerennn seru bgt baru pertama kali liat candi ...,"5,0\n/5",14 May 2023,"4,5/5\n(\n3.5rb Review\n)",IDR 50.000,"Prambanan, Sleman"
3,Legenda Roro Jonggrang Prambanan,"Pertunjukan yang memukau, ceritanya tersampaik...","5,0\n/5",20 Sep 2024,"4,7/5\n(\n78 Review\n)",IDR 100.000,"Prambanan, Sleman"
4,Candi Ratu Boko,Lokasi yg sudah dapat dijangkau dengan kendara...,"4,0\n/5",6 Jan 2025,"4,8/5\n(\n182 Review\n)",IDR 21.000,"Prambanan, Sleman"

In [49]:
# simpan ke csv
destinations_df.to_csv("dataset/destinations.csv", index=False)